-- ─────────────────────────────────────────────────────────────────────────────
-- document_verifications
-- Stores a verification record for every PDF generated by Nhance.
-- The token (UUID) is embedded in the QR code on each document.
-- Scanning the QR opens /verify/<token> — a public page that shows
-- the genuine document details, confirming the document was issued by the company.
--
-- Run once in Supabase SQL Editor.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS document_verifications (
  token        UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id   UUID        NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  doc_type     TEXT        NOT NULL,   -- invoice | quote | so | dc | cn | bill | po | vc | payment_received | payment_made
  doc_number   TEXT        NOT NULL,
  doc_date     DATE,
  party_name   TEXT,                   -- client or vendor name
  amount       NUMERIC(15,2),
  status       TEXT        NOT NULL DEFAULT 'active',  -- active | void | cancelled
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for fast token lookup on the public verify page
CREATE INDEX IF NOT EXISTS document_verifications_token_idx ON document_verifications(token);

-- Index for company queries (admin listing)
CREATE INDEX IF NOT EXISTS document_verifications_company_idx ON document_verifications(company_id, created_at DESC);

-- ── Row Level Security ────────────────────────────────────────────────────────
ALTER TABLE document_verifications ENABLE ROW LEVEL SECURITY;

-- Authenticated company members can INSERT and SELECT their own records
CREATE POLICY "Company members manage own verifications"
ON document_verifications
FOR ALL
TO authenticated
USING (
  company_id = (SELECT company_id FROM user_profiles WHERE id = auth.uid())
)
WITH CHECK (
  company_id = (SELECT company_id FROM user_profiles WHERE id = auth.uid())
);

-- Public (anon) can SELECT any record by token.
-- The token is a 128-bit UUID — unguessable without the physical document.
-- Only exposes what's already printed on the document itself.
CREATE POLICY "Public verification lookup by token"
ON document_verifications
FOR SELECT
TO anon
USING (true);
