import assert from 'node:assert/strict'
import test from 'node:test'
import * as XLSX from 'xlsx'
import { ACTIVITY_SECTIONS, activityBounds, activityDate, activityFields, activityMonthBounds, activityMonthDays, activityReference, activitySection, activitySectionCounts, activityTimestamp, fetchActivityRange, fetchActivityStart, filterActivity, redactActivity, shiftActivityDate, validActivityDate } from '../src/lib/dailyActivity.js'
import { createDailyActivityPDF, createDailyActivityWorkbook, dailyActivityCSV, dailyActivityJSON } from '../src/lib/dailyActivityExport.js'
import { activityFixture, capturedBusinessTables, companyId, fakeActivityDB } from './dailyActivity.fixture.mjs'

const bounds = activityBounds('2026-10-03')
const daily = activityFixture.slice(0, 5).map(redactActivity)
const report = { events: daily, date: '2026-10-03', companyName: 'Nhance Test', total: 5, highWater: 5, loadedAt: '2026-10-08T06:00:00Z', historyStart: '2026-09-30', filterDescription: 'All sections | All users | All actions' }
test('India day uses inclusive midnight and exclusive next midnight independent of browser zone', async () => {
  assert.deepEqual(bounds, { start: '2026-10-02T18:30:00.000Z', end: '2026-10-03T18:30:00.000Z' })
  assert.equal(activityDate('2026-10-03T18:29:59.999999Z'), '2026-10-03')
  assert.equal(activityDate('2026-10-03T18:30:00Z'), '2026-10-04')
  assert.match(activityTimestamp('2026-10-02T18:30:00Z'), /00:00:00/)
  assert.equal(validActivityDate('2026-02-30'), false)
  assert.throws(() => activityBounds('2026-02-30'), /valid activity date/)
  assert.equal(shiftActivityDate('2028-02-28', 1), '2028-02-29')
  assert.equal(activityMonthDays('2028-02').length, 29)
  assert.equal(activityMonthBounds('2026-12').end, '2026-12-31T18:30:00.000Z')
  const result = await fetchActivityRange(fakeActivityDB(), companyId, bounds)
  assert.deepEqual(result.events.map(e => e.id), ['create', 'edit', 'delete', 'login', 'automatic'])
})
test('all 141 captured tables and future sections remain in reports, including automatic and custom events', () => {
  assert.equal(capturedBusinessTables.length, 141)
  for (const table of capturedBusinessTables) assert.ok(ACTIVITY_SECTIONS.includes(activitySection({ table_name: table })), table)
  assert.equal(activitySection({ table_name: 'ra_bill_measurements' }), 'RA Billing')
  assert.equal(activitySection({ table_name: 'shift_fuel_entries', module: 'equipment' }), 'Fuel & Reconciliation')
  assert.equal(activitySection({ table_name: 'equipment_deployment_plans' }), 'Hire & Deployments')
  assert.equal(activitySection({ table_name: 'new_feature', module: 'new_module' }), 'Other / System')
  assert.equal(activitySection({ table_name: 'auth', module: 'auth', source: 'application_event' }), 'Authentication')
  assert.equal(Object.values(activitySectionCounts(daily)).reduce((a, b) => a + b, 0), daily.length)
  assert.equal(activityReference(daily[2]), 'ATT-001')
  assert.ok(activityFields(daily[1]).includes('notes'), 'A removed field must remain visible')
  assert.equal(filterActivity(daily, { actor: 'system' }).length, 1)
  assert.equal(filterActivity(daily, { section: 'Fuel & Reconciliation', actor: 'ravi', action: 'insert' }).length, 1)
  assert.equal(filterActivity(daily, { search: 'INV-001' }).length, 1)
  assert.equal(filterActivity(daily, { source: 'application_event' }).length, 1)
})
test('complete paging survives more than 1,000 events, small API caps and newly arriving events', async () => {
  const rows = Array.from({ length: 1503 }, (_, i) => ({ ...activityFixture[0], id: `event-${i}`, event_no: i + 1 }))
  const db = fakeActivityDB(rows, { cap: 137, append: { ...rows[0], id: 'later', event_no: 1504 } })
  const result = await fetchActivityRange(db, companyId, bounds)
  assert.equal(result.total, 1503)
  assert.equal(result.highWater, 1503)
  assert.equal(result.events.length, 1503)
  assert.equal(result.events.at(-1).id, 'event-1502')
  assert.ok(db.reads.length > 10)
  assert.ok(db.reads.every(read => read.filters.some(([op, key, value]) => op === 'eq' && key === 'company_id' && value === companyId)))
  const summary = await fetchActivityRange(fakeActivityDB(), companyId, activityMonthBounds('2026-10'), { summary: true })
  assert.equal(summary.total, 7)
  assert.equal(summary.events[0].old_data, undefined)
  assert.ok(await fetchActivityStart(fakeActivityDB(), companyId))
})
test('no partial, duplicate, foreign-company or count-unverified report can be downloaded', async () => {
  await assert.rejects(fetchActivityRange(fakeActivityDB(), '', bounds), /Select a company/)
  await assert.rejects(fetchActivityRange(fakeActivityDB([], { fail: true }), companyId, bounds), /Permission denied/)
  await assert.rejects(fetchActivityRange(fakeActivityDB(activityFixture, { missingCount: true }), companyId, bounds), /complete activity count/)
  await assert.rejects(fetchActivityRange(fakeActivityDB(activityFixture, { cap: 2, empty: true }), companyId, bounds), /incomplete/)
  await assert.rejects(fetchActivityRange(fakeActivityDB(activityFixture, { cap: 2, duplicate: true }), companyId, bounds), /snapshot mismatch/)
  await assert.rejects(fetchActivityRange(fakeActivityDB(activityFixture, { foreign: true }), companyId, bounds), /snapshot mismatch/)
  assert.equal((await fetchActivityRange(fakeActivityDB(), companyId, activityBounds('2026-01-01'))).total, 0)
})
test('all export formats preserve matching events, deletion evidence, before/after values and redaction', async () => {
  const json = dailyActivityJSON(report), csv = dailyActivityCSV(report)
  assert.equal(JSON.parse(json).events.length, 5)
  assert.equal(JSON.parse(json).events[2].old_data.employee_name, 'Ravi')
  assert.equal(JSON.parse(json).events[1].old_data.total_amount, 1000)
  assert.equal(JSON.parse(json).events[1].new_data.total_amount, 1180)
  assert.ok(!json.includes('NEVER-EXPORT') && !csv.includes('ALSO-SECRET'))
  assert.ok(csv.includes('[REDACTED]'))
  assert.ok(csv.includes('Station'))
  const book = await createDailyActivityWorkbook(report)
  const roundTrip = XLSX.read(XLSX.write(book, { type: 'buffer', bookType: 'xlsx' }), { type: 'buffer' })
  const activities = XLSX.utils.sheet_to_json(roundTrip.Sheets.Activities, { header: 1 })
  assert.equal(activities.length, 6)
  assert.equal(roundTrip.Sheets.Activities.A2.t, 'n')
  const values = XLSX.utils.sheet_to_json(roundTrip.Sheets['Record values'])
  assert.ok(values.some(r => r['Event #'] === 3 && r.Field === 'employee_name' && r.Snapshot === 'Before' && r['Value (JSON)'] === '"Ravi"'))
  const pdf = await createDailyActivityPDF(report)
  assert.ok(pdf.output().includes('FUEL-001'))
  assert.ok(pdf.output().includes('1180'))
  assert.ok(pdf.output().includes('Wrong attendance'))
  assert.ok(pdf.output().includes('removed'))
  assert.ok(pdf.getNumberOfPages() >= 2)
})
test('Excel losslessly splits long record values and complete event JSON into numbered parts', async () => {
  const long = 'LONG,'.repeat(15000)
  const event = { ...daily[1], new_data: { notes: long }, changed_fields: ['notes'] }
  const book = await createDailyActivityWorkbook({ ...report, events: [event], total: 1 })
  const values = XLSX.utils.sheet_to_json(book.Sheets['Record values']).filter(row => row.Field === 'notes' && row.Snapshot === 'After')
  assert.equal(values.map(row => row['Value (JSON)']).join(''), JSON.stringify(long))
  assert.ok(values.every(row => row['Value (JSON)'].length <= 29000))
  const raw = XLSX.utils.sheet_to_json(book.Sheets['Event JSON'])
  assert.equal(JSON.parse(raw.map(row => row['JSON (concatenate parts in order)']).join('')).new_data.notes, long)
  const empty = await createDailyActivityPDF({ ...report, events: [], total: 0, highWater: null })
  assert.match(empty.output(), /No recorded activities/)
})
