import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { createServer } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'
import { chromium } from 'playwright'

const root = resolve('.')
const temporary = await mkdtemp(join(root, '.navigation-browser-'))
const artifacts = resolve(process.env.NAVIGATION_ARTIFACT_DIR || 'test-artifacts/navigation')
await mkdir(artifacts, { recursive: true })
const id = number => `00000000-0000-4000-8000-${String(number).padStart(12, '0')}`
const user = id(1), otherUser = id(2), company = id(3), otherCompany = id(4)
const notifications = [
  { id: id(10), company_id: company, user_id: null, type: 'incident_breakdown', title: 'Breakdown — EX-001', body: 'Excavator stopped during the morning shift.', is_read: false, created_at: '2026-10-01T04:10:00Z' },
  { id: id(11), company_id: company, user_id: user, type: 'outstanding_dues', title: 'Outstanding dues — Site A', body: 'Invoice remains unpaid on the completed project.', is_read: false, created_at: '2026-10-01T04:00:00Z' },
  { id: id(12), company_id: company, user_id: otherUser, type: 'info', title: 'Private alert for another user', is_read: false, created_at: '2026-10-01T03:00:00Z' },
  { id: id(13), company_id: otherCompany, user_id: null, type: 'info', title: 'Another company alert', is_read: false, created_at: '2026-10-01T02:00:00Z' },
  { id: id(14), company_id: company, user_id: null, type: 'info', title: 'Earlier operational update', is_read: true, created_at: '2026-10-01T01:00:00Z' },
]
await writeFile(join(temporary, 'auth.js'), `export const useAuth=()=>{const q=new URLSearchParams(location.search);return {companyId:q.has('foreign')?'${otherCompany}':'${company}',company:{name:'SRA Mining and Constructions'},role:q.has('operator')?'operator':'admin',session:{user:{id:q.has('other-user')?'${otherUser}':'${user}'}},hasModule:()=>true}};`)
await writeFile(join(temporary, 'display.js'), `export const useDisplayMode=()=>({mode:'advanced',setMode:()=>{}});export const useTheme=()=>({theme:'dark',toggle:()=>{document.documentElement.setAttribute('data-theme',document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark')}});`)
await writeFile(join(temporary, 'supabase.js'), `const notifications=${JSON.stringify(notifications)};export const supabase={from(table){const filters={};const q={select(){return q},eq(key,value){filters[key]=value;return q},or(value){filters.recipient=value;return q},in(){return q},order(){return q},limit(){return q},then(resolve){window.queries=(window.queries||[]).concat({table,filters});if(table==='notifications'){if(location.search.includes('notification-error')&&!window.recovered)return Promise.resolve({error:{message:'Network unavailable'}}).then(resolve);const data=location.search.includes('empty')?[]:notifications.filter(row=>row.company_id===filters.company_id&&(row.user_id===null||filters.recipient.includes(row.user_id)));return Promise.resolve({data,error:null}).then(resolve)}if(table==='approval_task_inbox'&&location.search.includes('legacy'))return Promise.resolve({error:{code:'PGRST205',message:'Could not find the table approval_task_inbox'}}).then(resolve);return Promise.resolve({count:3,error:null}).then(resolve)}};return q}};`)
await writeFile(join(temporary, 'index.html'), '<div id="root"></div><script type="module" src="/main.jsx"></script>')
await writeFile(join(temporary, 'main.jsx'), `import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import {QueryClient,QueryClientProvider} from '@tanstack/react-query';import TopBar from ${JSON.stringify(join(root, 'src/components/layout/TopBar.jsx'))};import RightBar from ${JSON.stringify(join(root, 'src/components/layout/RightBar.jsx'))};import ${JSON.stringify(join(root, 'src/index.css'))};document.documentElement.setAttribute('data-theme','dark');function Preview(){const [page,setPage]=useState('dashboard');return <div className="flex h-screen bg-dark-900"><div className="hidden lg:flex w-60 flex-col bg-dark-800 border-r border-dark-600 p-6"><div className="text-xl font-bold text-primary-400">NHANCE</div><p className="text-xs text-slate-500 mt-2">Fleet & operations</p><div className="text-sm mt-10 text-slate-300">Dashboard</div><div className="text-sm mt-6 text-slate-500">Equipments & Machineries</div><div className="text-sm mt-6 text-slate-500">Daily Operations</div><div className="text-sm mt-6 text-slate-500">Fuel Reconciliation</div></div><div className="flex flex-1 min-w-0 flex-col"><TopBar activePage={page} onNavigate={setPage} onMenuToggle={()=>{}}/><main className="flex-1 p-6 min-w-0"><h2 data-testid="current-page" className="text-lg font-bold text-slate-100">{page==='approval_center'?'Approval Centre':page==='dashboard'?'Operations overview':page}</h2><p className="text-sm text-slate-500 mt-2">Your fleet and project updates at a glance</p><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">{['Active equipment','Open projects','Daily operations'].map((label,index)=><div key={label} className="p-5 rounded-xl bg-dark-800 border border-dark-600"><p className="text-sm text-slate-400">{label}</p><p className="text-2xl font-bold text-slate-100 mt-3">{[18,6,24][index]}</p></div>)}</div></main></div>{page!=='chat'&&<RightBar activePage={page} onNavigate={setPage}/>}</div>}createRoot(document.getElementById('root')).render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><Preview/></QueryClientProvider>);`)
const server = await createServer({ configFile: false, root: temporary, plugins: [react(), { name: 'mock-navigation-data', enforce: 'pre', resolveId(source) {
  if (/\/supabase(\.js)?$/.test(source)) return join(temporary, 'supabase.js')
  if (/\/AuthContext(\.jsx)?$/.test(source)) return join(temporary, 'auth.js')
  if (/\/(DisplayModeContext|ThemeContext)(\.jsx)?$/.test(source)) return join(temporary, 'display.js')
} }], css: { postcss: { plugins: [tailwindcss({ config: join(root, 'tailwind.config.js') }), autoprefixer()] } }, server: { host: '127.0.0.1', port: 4180, fs: { allow: [root] } } })
let browser
try {
  await server.listen()
  browser = await chromium.launch(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE, args: ['--no-sandbox'] } : {})
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } })
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('http://127.0.0.1:4180')
  const rail = page.locator('.nhance-rightbar')
  const approval = rail.getByRole('button', { name: 'Approval Centre, 3 pending approvals', exact: true })
  await approval.waitFor()
  assert.equal(await approval.locator('svg circle').count(), 1)
  assert.equal(await approval.locator('.lucide-bell').count(), 0)
  assert.equal(await page.locator('.nhance-topbar').getByRole('button', { name: /Approval Centre/ }).isVisible(), false)
  const bell = page.getByRole('button', { name: 'Notifications', exact: true })
  await bell.getByLabel('2 unread notifications').waitFor()
  await approval.click()
  assert.equal(await page.getByTestId('current-page').innerText(), 'Approval Centre')
  assert.equal(await approval.getAttribute('aria-current'), 'page')
  await bell.click()
  const panel = page.getByRole('dialog', { name: 'Notifications', exact: true })
  await panel.waitFor()
  assert.equal(await panel.getByText('Private alert for another user').count(), 0)
  assert.equal(await panel.getByText('Another company alert').count(), 0)
  await panel.getByText('Breakdown — EX-001').waitFor()
  await page.screenshot({ path: join(artifacts, 'approval-notifications-desktop.png'), fullPage: true })
  await panel.getByRole('button', { name: /Mark all read/ }).click()
  assert.equal(await bell.getByLabel('2 unread notifications').count(), 0)
  assert.equal(await approval.isVisible(), true)
  await page.reload()
  await approval.waitFor()
  await bell.click()
  await panel.getByText('You’re all caught up').waitFor()
  await page.keyboard.press('Escape')
  assert.equal(await panel.count(), 0)
  assert.equal(await bell.evaluate(element => element === document.activeElement), true)
  await page.goto('http://127.0.0.1:4180?other-user')
  await bell.getByLabel('2 unread notifications').waitFor()
  await bell.click()
  await panel.getByText('Private alert for another user').waitFor()
  assert.equal(await panel.getByText('Outstanding dues — Site A').count(), 0)
  await panel.getByText('Breakdown — EX-001').click()
  assert.equal(await page.getByTestId('current-page').innerText(), 'fleet')
  await page.goto('http://127.0.0.1:4180?foreign')
  await bell.getByLabel('1 unread notifications').waitFor()
  await bell.click()
  await panel.getByText('Another company alert').waitFor()
  assert.equal(await panel.getByText('Breakdown — EX-001').count(), 0)
  await page.goto('http://127.0.0.1:4180?notification-error')
  await bell.click()
  await panel.getByRole('alert').waitFor()
  assert.equal(await panel.getByText('You’re all caught up').count(), 0)
  await page.evaluate(() => { window.recovered = true })
  await panel.getByRole('button', { name: 'Try again' }).click()
  await panel.getByText('Breakdown — EX-001').waitFor()
  await page.goto('http://127.0.0.1:4180?empty')
  await bell.click()
  await panel.getByText('No notifications yet').waitFor()
  await page.goto('http://127.0.0.1:4180?legacy')
  await approval.waitFor()
  assert.equal((await page.evaluate(() => window.queries)).some(query => query.table === 'approval_requests'), true)
  await page.goto('http://127.0.0.1:4180?operator')
  await bell.waitFor()
  assert.equal(await page.getByRole('button', { name: /Approval Centre/ }).count(), 0)
  await page.goto('http://127.0.0.1:4180')
  await rail.getByRole('button', { name: 'Team Chat', exact: true }).click()
  assert.equal(await rail.count(), 0)
  await page.locator('.nhance-topbar').getByRole('button', { name: /Approval Centre/ }).click()
  await approval.waitFor()
  await page.setViewportSize({ width: 390, height: 844 })
  const mobileApproval = page.locator('.nhance-topbar').getByRole('button', { name: /Approval Centre/ })
  assert.equal(await mobileApproval.isVisible(), true)
  assert.equal(await rail.isVisible(), false)
  await bell.click()
  await panel.waitFor()
  const bounds = await panel.boundingBox()
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await page.screenshot({ path: join(artifacts, 'approval-notifications-mobile.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 320, height: 640 })
  await bell.click()
  const smallBounds = await panel.boundingBox()
  assert.ok(smallBounds.x >= 0 && smallBounds.x + smallBounds.width <= 320)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.getByRole('button', { name: 'Switch to light mode' }).click()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light')
  await page.screenshot({ path: join(artifacts, 'approval-notifications-light.png'), fullPage: true })
  assert.deepEqual(errors, [])
  console.log('Navigation browser checks passed: approval icon/rail, independent counts, recipient/company filters, read persistence, error recovery, legacy approvals, permissions, Chat fallback, responsive panels and themes.')
} finally { await browser?.close(); await server.close(); await rm(temporary, { recursive: true, force: true }) }
