-- LEGACY NOTICE
--
-- The original client-writable audit_logs migration has been superseded.
-- Do not apply an audit schema from src/migrations.
--
-- The canonical, deployment-managed implementation is:
--   supabase/migrations/20260930101826_tamper_evident_audit_ledger.sql
--
-- It provides database-triggered before/after snapshots, deletion retention,
-- least-privilege access, immutable DML/TRUNCATE protection, automatic trigger
-- coverage for future tables, and per-company SHA-256 chain verification.

